### ISSUE TITLE
asdf does something similar

### ISSUE THREAD

**Issue by atgreen** [jordan4ibanez/super-loader#1]
Not really an issue, but just pointing out that you can get similar behavior by just doing this:

```
(asdf:initialize-source-registry '(:source-registry :ignore-inherited-configuration (:tree (uiop:getcwd))))
```
When you run `asdf:load-system`, it will search all subdirs from your current directory for the system's asd file and load it.

**Comment by jordan4ibanez** [comment]
> Not really an issue, but just pointing out that you can get similar behavior by just doing this:
> 
> ```
> (asdf:initialize-source-registry '(:source-registry :ignore-inherited-configuration (:tree (uiop:getcwd))))
> ```
> 
> When you run `asdf:load-system`, it will search all subdirs from your current directory for the system's asd file and load it.

Yes, that is quite a possibility. But there is a few problems with this implementation. 

1.) You have no control over it. 
Say you have found that you no longer need a local system. You have migrated a system into another one due to redundancy. Etc etc etc. You're on the fence about deleting it because you have created a lot of excellent reference material. You could delete the ``asd`` file, rename it, move it, whatever. OR, you could simply comment out the ``super-load`` in the source code of the entry point into your program. Maybe there's something in that ``asd`` you want to reference in the future as well.

2.) You have an older system that you want to use, but you find that you want to rebuild it from the ground up in your IDE and you don't want it to load while you're manufacturing a new system in a directory next to it. Again, you could delete the ``asd`` file in it. But if you forget to do this, oops you have accidentally shipped the original version and your rebuilt version of it. The solution could simply be, ``super-load`` your new system you're manufacturing while not having to even worry about the dead system even being in the project while you're working.

3.) If your project becomes extremely complex with file hierarchy, let's say you have a git book in the root of the project, or maybe you're storing a lot of assets in specific domains within this file hierarchy for a game. You could use this tree technique to load it up at the cost of it having to waste time searching through all the folders to find systems. Or you could just tell it directly where your systems are using ``super-load`` and skip having the system do all that work.

This is all coming from a game developer's point of view. A fairly new developer into Common Lisp as well. This is not only a more explicit way to visualize your program loading a system into the image. This is also an easier way for new developers to learn how to develop asdf systems. It does not have to be a rust-level learning curve for new users to learn how to load systems.

This is coming from the point of view where there is no quicklisp library (that I could find) to directly load systems from your local folder as it is in a majority of other languages. Spending over a week straight trying to devise an easy solution in the mindset of "How would a new developer be able to do this? They have to move their systems out of the root folder of their project when there could be a much easier way to do this." Every developer should not have to roll their own, that's why we have quicklisp in the first place. :D

In creating this micro system (super-loader), not only does this create a more efficient and explicit way to load local systems into the image, this lowers the barrier of entry for new developers to learn Common Lisp. Because instead of having to search through google, texts, forums where the collective response is basically "Oh you have to push to the source registry or the old way with push to the global registry". With this in the quicklisp repository you can just load up super-loader with quicklisp then start loading your systems.

An alternative solution to this micro system, is asfd or perhaps quicklisp being able to intake a local path, somehow. I do not for-see this becoming an implemented solution to this as there hasn't been one yet.

I would like to hear your opinion on this last option, because even if you do not add in super-loader into the quicklisp repository, being able to load systems like this is an extremely advantageous implementation. Especially if you're trying to make two systems work together then break them up later as optionally codependent, or learning, or rapid prototyping. The folder can easily be pulled out later when you're satisfied with what you have created.

**Comment by atgreen** [comment]
Yea, I agree with many of your comments, and you are expressing some of the reasons I developed ocicl as an alternative to quicklisp.   Check it out here: https://github.com/ocicl/ocicl

**Comment by jordan4ibanez** [comment]
I must admit, I appreciate your sentiment towards what I have said and the alternative to quicklisp. But this has left me a bit on edge with one final question:
So does this mean super-loader will not be added to the quicklisp repo?

**Comment by atgreen** [comment]
I have nothing to do with quicklisp.  I tried adding it to the ocicl repo, but it seems that it has a hard dependency on quicklisp.  https://github.com/ocicl/super-loader/actions/runs/6023888208/job/16341496836

**Comment by jordan4ibanez** [comment]
> I have nothing to do with quicklisp. I tried adding it to the ocicl repo, but it seems that it has a hard dependency on quicklisp. https://github.com/ocicl/super-loader/actions/runs/6023888208/job/16341496836

Very sorry, I must need more sleep. Yes, for now, quicklisp is a hard dep. If you happen to toy around with it and find "hey, you can use asdf for the quicklisp part too!". Feel free to open another issue.
